---
steps:
  - type: get
    daemon: zebra
    description: |
      1. Проверка подключения

      gRPC проверка чтения CONFIG tree.

      Аналог частично близок к:

      vtysh:
      show running-config

      requestType:
      1 = CONFIG ONLY


      Демон: zebra

      YANG/lib:
      endpoint: zebra / localhost:50051
      YANG modules:
      - frr-vrf.yang
      root paths/libs:
      - /frr-vrf:lib


      grpcurl пример:
      grpcurl -plaintext -d @ localhost:50051 frr.Northbound/Get <<'JSON'
      {
        "type": "CONFIG",
        "encoding": "JSON",
        "path": [
          "/frr-vrf:lib"
        ]
      }
      JSON
    params:
      requestType: 1
      path:
        - "/frr-vrf:lib"
