---
steps:
  - type: getCapabilities
    daemon: zebra
    description: |
      STEP 4

      Получение возможностей gRPC API FRR.

      Возвращает:
        - версию FRR
        - supported YANG modules
        - supported encodings
        - supported trees

      Аналога во vtysh нет.

      Используется для:
        - discovery
        - понимания API
        - поиска доступных YANG modules


      Демон: zebra

      YANG/lib:
      endpoint: zebra / localhost:50051
      RPC: GetCapabilities() возвращает supported YANG modules этого daemon endpoint.
      ожидаемый daemon module: frr-zebra.yang

      grpcurl пример:
      grpcurl -plaintext localhost:50051 frr.Northbound/GetCapabilities
