frr version 10.6.1
frr defaults traditional
hostname 9bc25ba7e61a
log stdout
log file /var/log/frr/frr.log
log record-priority
log timestamp precision 3
service integrated-vtysh-config
!
debug northbound callbacks configuration
debug northbound callbacks state
debug northbound callbacks rpc
debug northbound callbacks notify
debug mgmt backend
debug mgmt frontend
!
segment-routing
 traffic-eng
 exit
exit
!
