frr version 10.6
frr defaults traditional
hostname frr
service integrated-vtysh-config

log stdout debugging
log file /var/log/frr/frr.log debugging

log record-priority
log timestamp precision 3

debug mgmt frontend
debug mgmt backend
debug mgmt txn
debug northbound callbacks
debug northbound transactions

!
end