// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright 2019 FRRouting
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
// BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
// OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
// THE POSSIBILITY OF SUCH DAMAGE.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: frrpb/frr.proto

package frrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported encodings for YANG instance data.
type Encoding int32

const (
	Encoding_JSON Encoding = 0
	Encoding_XML  Encoding = 1
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "JSON",
		1: "XML",
	}
	Encoding_value = map[string]int32{
		"JSON": 0,
		"XML":  1,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_frrpb_frr_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_frrpb_frr_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{0}
}

// Type of elements within the data tree.
type GetRequest_DataType int32

const (
	// All data elements.
	GetRequest_ALL GetRequest_DataType = 0
	// Config elements.
	GetRequest_CONFIG GetRequest_DataType = 1
	// State elements.
	GetRequest_STATE GetRequest_DataType = 2
)

// Enum value maps for GetRequest_DataType.
var (
	GetRequest_DataType_name = map[int32]string{
		0: "ALL",
		1: "CONFIG",
		2: "STATE",
	}
	GetRequest_DataType_value = map[string]int32{
		"ALL":    0,
		"CONFIG": 1,
		"STATE":  2,
	}
)

func (x GetRequest_DataType) Enum() *GetRequest_DataType {
	p := new(GetRequest_DataType)
	*p = x
	return p
}

func (x GetRequest_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetRequest_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_frrpb_frr_proto_enumTypes[1].Descriptor()
}

func (GetRequest_DataType) Type() protoreflect.EnumType {
	return &file_frrpb_frr_proto_enumTypes[1]
}

func (x GetRequest_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetRequest_DataType.Descriptor instead.
func (GetRequest_DataType) EnumDescriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{2, 0}
}

type LoadToCandidateRequest_LoadType int32

const (
	// Merge the data tree into the candidate configuration.
	LoadToCandidateRequest_MERGE LoadToCandidateRequest_LoadType = 0
	// Replace the candidate configuration by the provided data tree.
	LoadToCandidateRequest_REPLACE LoadToCandidateRequest_LoadType = 1
)

// Enum value maps for LoadToCandidateRequest_LoadType.
var (
	LoadToCandidateRequest_LoadType_name = map[int32]string{
		0: "MERGE",
		1: "REPLACE",
	}
	LoadToCandidateRequest_LoadType_value = map[string]int32{
		"MERGE":   0,
		"REPLACE": 1,
	}
)

func (x LoadToCandidateRequest_LoadType) Enum() *LoadToCandidateRequest_LoadType {
	p := new(LoadToCandidateRequest_LoadType)
	*p = x
	return p
}

func (x LoadToCandidateRequest_LoadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadToCandidateRequest_LoadType) Descriptor() protoreflect.EnumDescriptor {
	return file_frrpb_frr_proto_enumTypes[2].Descriptor()
}

func (LoadToCandidateRequest_LoadType) Type() protoreflect.EnumType {
	return &file_frrpb_frr_proto_enumTypes[2]
}

func (x LoadToCandidateRequest_LoadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadToCandidateRequest_LoadType.Descriptor instead.
func (LoadToCandidateRequest_LoadType) EnumDescriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{12, 0}
}

type CommitRequest_Phase int32

const (
	// Validate if the configuration changes are valid (phase 0).
	CommitRequest_VALIDATE CommitRequest_Phase = 0
	// Prepare resources to apply the configuration changes (phase 1).
	CommitRequest_PREPARE CommitRequest_Phase = 1
	// Release previously allocated resources (phase 2).
	CommitRequest_ABORT CommitRequest_Phase = 2
	// Apply the configuration changes (phase 2).
	CommitRequest_APPLY CommitRequest_Phase = 3
	// All of the above (VALIDATE + PREPARE + ABORT/APPLY).
	//
	// This option can't be used to implement network-wide transactions,
	// since they require the manager entity to take into account the results
	// of the preparation phase of multiple managed devices.
	CommitRequest_ALL CommitRequest_Phase = 4
)

// Enum value maps for CommitRequest_Phase.
var (
	CommitRequest_Phase_name = map[int32]string{
		0: "VALIDATE",
		1: "PREPARE",
		2: "ABORT",
		3: "APPLY",
		4: "ALL",
	}
	CommitRequest_Phase_value = map[string]int32{
		"VALIDATE": 0,
		"PREPARE":  1,
		"ABORT":    2,
		"APPLY":    3,
		"ALL":      4,
	}
)

func (x CommitRequest_Phase) Enum() *CommitRequest_Phase {
	p := new(CommitRequest_Phase)
	*p = x
	return p
}

func (x CommitRequest_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommitRequest_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_frrpb_frr_proto_enumTypes[3].Descriptor()
}

func (CommitRequest_Phase) Type() protoreflect.EnumType {
	return &file_frrpb_frr_proto_enumTypes[3]
}

func (x CommitRequest_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommitRequest_Phase.Descriptor instead.
func (CommitRequest_Phase) EnumDescriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{14, 0}
}

// RPC: GetCapabilities()
type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{0}
}

type GetCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FRR version.
	FrrVersion string `protobuf:"bytes,1,opt,name=frr_version,json=frrVersion,proto3" json:"frr_version,omitempty"`
	// Indicates whether FRR was compiled with support for configuration
	// rollbacks or not (--enable-config-rollbacks).
	RollbackSupport bool `protobuf:"varint,2,opt,name=rollback_support,json=rollbackSupport,proto3" json:"rollback_support,omitempty"`
	// Supported schema modules.
	SupportedModules []*ModuleData `protobuf:"bytes,3,rep,name=supported_modules,json=supportedModules,proto3" json:"supported_modules,omitempty"`
	// Supported encodings.
	SupportedEncodings []Encoding `protobuf:"varint,4,rep,packed,name=supported_encodings,json=supportedEncodings,proto3,enum=frr.Encoding" json:"supported_encodings,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapabilitiesResponse) GetFrrVersion() string {
	if x != nil {
		return x.FrrVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetRollbackSupport() bool {
	if x != nil {
		return x.RollbackSupport
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSupportedModules() []*ModuleData {
	if x != nil {
		return x.SupportedModules
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetSupportedEncodings() []Encoding {
	if x != nil {
		return x.SupportedEncodings
	}
	return nil
}

// RPC: Get()
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of data being requested.
	Type GetRequest_DataType `protobuf:"varint,1,opt,name=type,proto3,enum=frr.GetRequest_DataType" json:"type,omitempty"`
	// Encoding to be used.
	Encoding Encoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=frr.Encoding" json:"encoding,omitempty"`
	// Include implicit default nodes.
	WithDefaults bool `protobuf:"varint,3,opt,name=with_defaults,json=withDefaults,proto3" json:"with_defaults,omitempty"`
	// Paths requested by the client.
	Path          []string `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetType() GetRequest_DataType {
	if x != nil {
		return x.Type
	}
	return GetRequest_ALL
}

func (x *GetRequest) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_JSON
}

func (x *GetRequest) GetWithDefaults() bool {
	if x != nil {
		return x.WithDefaults
	}
	return false
}

func (x *GetRequest) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp in nanoseconds since Epoch.
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The requested data.
	Data          *DataTree `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetResponse) GetData() *DataTree {
	if x != nil {
		return x.Data
	}
	return nil
}

// RPC: CreateCandidate()
type CreateCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateRequest) Reset() {
	*x = CreateCandidateRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateRequest) ProtoMessage() {}

func (x *CreateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateRequest.ProtoReflect.Descriptor instead.
func (*CreateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{4}
}

type CreateCandidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Handle to the new created candidate configuration.
	CandidateId   uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateResponse) Reset() {
	*x = CreateCandidateResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateResponse) ProtoMessage() {}

func (x *CreateCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateResponse.ProtoReflect.Descriptor instead.
func (*CreateCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCandidateResponse) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

// RPC: DeleteCandidate()
type DeleteCandidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Candidate configuration to delete.
	CandidateId   uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCandidateRequest) Reset() {
	*x = DeleteCandidateRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateRequest) ProtoMessage() {}

func (x *DeleteCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateRequest.ProtoReflect.Descriptor instead.
func (*DeleteCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCandidateRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

type DeleteCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCandidateResponse) Reset() {
	*x = DeleteCandidateResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateResponse) ProtoMessage() {}

func (x *DeleteCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateResponse.ProtoReflect.Descriptor instead.
func (*DeleteCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{7}
}

// RPC: UpdateCandidate()
type UpdateCandidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Candidate configuration to update.
	CandidateId   uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCandidateRequest) Reset() {
	*x = UpdateCandidateRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateRequest) ProtoMessage() {}

func (x *UpdateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateRequest.ProtoReflect.Descriptor instead.
func (*UpdateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCandidateRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

type UpdateCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCandidateResponse) Reset() {
	*x = UpdateCandidateResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateResponse) ProtoMessage() {}

func (x *UpdateCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateResponse.ProtoReflect.Descriptor instead.
func (*UpdateCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{9}
}

// RPC: EditCandidate()
type EditCandidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Candidate configuration that is going to be edited.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Data elements to be created or updated.
	Update []*PathValue `protobuf:"bytes,2,rep,name=update,proto3" json:"update,omitempty"`
	// Paths to be deleted from the data tree.
	Delete        []*PathValue `protobuf:"bytes,3,rep,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCandidateRequest) Reset() {
	*x = EditCandidateRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCandidateRequest) ProtoMessage() {}

func (x *EditCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCandidateRequest.ProtoReflect.Descriptor instead.
func (*EditCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{10}
}

func (x *EditCandidateRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *EditCandidateRequest) GetUpdate() []*PathValue {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *EditCandidateRequest) GetDelete() []*PathValue {
	if x != nil {
		return x.Delete
	}
	return nil
}

type EditCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCandidateResponse) Reset() {
	*x = EditCandidateResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCandidateResponse) ProtoMessage() {}

func (x *EditCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCandidateResponse.ProtoReflect.Descriptor instead.
func (*EditCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{11}
}

// RPC: LoadToCandidate()
type LoadToCandidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Candidate configuration that is going to be edited.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Load operation to apply.
	Type LoadToCandidateRequest_LoadType `protobuf:"varint,2,opt,name=type,proto3,enum=frr.LoadToCandidateRequest_LoadType" json:"type,omitempty"`
	// Configuration data.
	Config        *DataTree `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadToCandidateRequest) Reset() {
	*x = LoadToCandidateRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadToCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadToCandidateRequest) ProtoMessage() {}

func (x *LoadToCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadToCandidateRequest.ProtoReflect.Descriptor instead.
func (*LoadToCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{12}
}

func (x *LoadToCandidateRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *LoadToCandidateRequest) GetType() LoadToCandidateRequest_LoadType {
	if x != nil {
		return x.Type
	}
	return LoadToCandidateRequest_MERGE
}

func (x *LoadToCandidateRequest) GetConfig() *DataTree {
	if x != nil {
		return x.Config
	}
	return nil
}

type LoadToCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadToCandidateResponse) Reset() {
	*x = LoadToCandidateResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadToCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadToCandidateResponse) ProtoMessage() {}

func (x *LoadToCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadToCandidateResponse.ProtoReflect.Descriptor instead.
func (*LoadToCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{13}
}

// RPC: Commit()
type CommitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Candidate configuration that is going to be committed.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Transaction phase.
	Phase CommitRequest_Phase `protobuf:"varint,2,opt,name=phase,proto3,enum=frr.CommitRequest_Phase" json:"phase,omitempty"`
	// Assign a comment to this commit.
	Comment       string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{14}
}

func (x *CommitRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *CommitRequest) GetPhase() CommitRequest_Phase {
	if x != nil {
		return x.Phase
	}
	return CommitRequest_VALIDATE
}

func (x *CommitRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CommitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the created configuration transaction (when the phase is APPLY
	// or ALL).
	TransactionId uint32 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Human-readable error or warning message(s).
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{15}
}

func (x *CommitResponse) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *CommitResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// RPC: ListTransactions()
type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{16}
}

type ListTransactionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction ID.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Client that committed the transaction.
	Client string `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	// Date and time the transaction was committed.
	Date string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	// Comment assigned to the transaction.
	Comment       string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{17}
}

func (x *ListTransactionsResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListTransactionsResponse) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ListTransactionsResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListTransactionsResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// RPC: GetTransaction()
type GetTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction to retrieve.
	TransactionId uint32 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Encoding to be used.
	Encoding Encoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=frr.Encoding" json:"encoding,omitempty"`
	// Include implicit default nodes.
	WithDefaults  bool `protobuf:"varint,3,opt,name=with_defaults,json=withDefaults,proto3" json:"with_defaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{18}
}

func (x *GetTransactionRequest) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *GetTransactionRequest) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_JSON
}

func (x *GetTransactionRequest) GetWithDefaults() bool {
	if x != nil {
		return x.WithDefaults
	}
	return false
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *DataTree              `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{19}
}

func (x *GetTransactionResponse) GetConfig() *DataTree {
	if x != nil {
		return x.Config
	}
	return nil
}

// RPC: LockConfig()
type LockConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockConfigRequest) Reset() {
	*x = LockConfigRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockConfigRequest) ProtoMessage() {}

func (x *LockConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockConfigRequest.ProtoReflect.Descriptor instead.
func (*LockConfigRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{20}
}

type LockConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockConfigResponse) Reset() {
	*x = LockConfigResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockConfigResponse) ProtoMessage() {}

func (x *LockConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockConfigResponse.ProtoReflect.Descriptor instead.
func (*LockConfigResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{21}
}

// RPC: UnlockConfig()
type UnlockConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockConfigRequest) Reset() {
	*x = UnlockConfigRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockConfigRequest) ProtoMessage() {}

func (x *UnlockConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockConfigRequest.ProtoReflect.Descriptor instead.
func (*UnlockConfigRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{22}
}

type UnlockConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockConfigResponse) Reset() {
	*x = UnlockConfigResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockConfigResponse) ProtoMessage() {}

func (x *UnlockConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockConfigResponse.ProtoReflect.Descriptor instead.
func (*UnlockConfigResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{23}
}

// RPC: Execute()
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path of the YANG RPC or YANG Action.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Input parameters.
	Input         []*PathValue `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_frrpb_frr_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{24}
}

func (x *ExecuteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExecuteRequest) GetInput() []*PathValue {
	if x != nil {
		return x.Input
	}
	return nil
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output parameters.
	Output        []*PathValue `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_frrpb_frr_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{25}
}

func (x *ExecuteResponse) GetOutput() []*PathValue {
	if x != nil {
		return x.Output
	}
	return nil
}

// YANG module.
type ModuleData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the YANG module;
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Organization publishing the module.
	Organization string `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	// Latest revision of the module;
	Revision      string `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleData) Reset() {
	*x = ModuleData{}
	mi := &file_frrpb_frr_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleData) ProtoMessage() {}

func (x *ModuleData) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleData.ProtoReflect.Descriptor instead.
func (*ModuleData) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{26}
}

func (x *ModuleData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleData) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *ModuleData) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

// Path-value pair representing a data element.
type PathValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// YANG data path.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Data value.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathValue) Reset() {
	*x = PathValue{}
	mi := &file_frrpb_frr_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathValue) ProtoMessage() {}

func (x *PathValue) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathValue.ProtoReflect.Descriptor instead.
func (*PathValue) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{27}
}

func (x *PathValue) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// YANG instance data.
type DataTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoding      Encoding               `protobuf:"varint,1,opt,name=encoding,proto3,enum=frr.Encoding" json:"encoding,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataTree) Reset() {
	*x = DataTree{}
	mi := &file_frrpb_frr_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTree) ProtoMessage() {}

func (x *DataTree) ProtoReflect() protoreflect.Message {
	mi := &file_frrpb_frr_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTree.ProtoReflect.Descriptor instead.
func (*DataTree) Descriptor() ([]byte, []int) {
	return file_frrpb_frr_proto_rawDescGZIP(), []int{28}
}

func (x *DataTree) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_JSON
}

func (x *DataTree) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_frrpb_frr_proto protoreflect.FileDescriptor

const file_frrpb_frr_proto_rawDesc = "" +
	"\n" +
	"\x0ffrrpb/frr.proto\x12\x03frr\"\x18\n" +
	"\x16GetCapabilitiesRequest\"\xe3\x01\n" +
	"\x17GetCapabilitiesResponse\x12\x1f\n" +
	"\vfrr_version\x18\x01 \x01(\tR\n" +
	"frrVersion\x12)\n" +
	"\x10rollback_support\x18\x02 \x01(\bR\x0frollbackSupport\x12<\n" +
	"\x11supported_modules\x18\x03 \x03(\v2\x0f.frr.ModuleDataR\x10supportedModules\x12>\n" +
	"\x13supported_encodings\x18\x04 \x03(\x0e2\r.frr.EncodingR\x12supportedEncodings\"\xca\x01\n" +
	"\n" +
	"GetRequest\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.frr.GetRequest.DataTypeR\x04type\x12)\n" +
	"\bencoding\x18\x02 \x01(\x0e2\r.frr.EncodingR\bencoding\x12#\n" +
	"\rwith_defaults\x18\x03 \x01(\bR\fwithDefaults\x12\x12\n" +
	"\x04path\x18\x04 \x03(\tR\x04path\"*\n" +
	"\bDataType\x12\a\n" +
	"\x03ALL\x10\x00\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x01\x12\t\n" +
	"\x05STATE\x10\x02\"N\n" +
	"\vGetResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12!\n" +
	"\x04data\x18\x02 \x01(\v2\r.frr.DataTreeR\x04data\"\x18\n" +
	"\x16CreateCandidateRequest\"<\n" +
	"\x17CreateCandidateResponse\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\rR\vcandidateId\";\n" +
	"\x16DeleteCandidateRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\rR\vcandidateId\"\x19\n" +
	"\x17DeleteCandidateResponse\";\n" +
	"\x16UpdateCandidateRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\rR\vcandidateId\"\x19\n" +
	"\x17UpdateCandidateResponse\"\x89\x01\n" +
	"\x14EditCandidateRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\rR\vcandidateId\x12&\n" +
	"\x06update\x18\x02 \x03(\v2\x0e.frr.PathValueR\x06update\x12&\n" +
	"\x06delete\x18\x03 \x03(\v2\x0e.frr.PathValueR\x06delete\"\x17\n" +
	"\x15EditCandidateResponse\"\xc0\x01\n" +
	"\x16LoadToCandidateRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\rR\vcandidateId\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.frr.LoadToCandidateRequest.LoadTypeR\x04type\x12%\n" +
	"\x06config\x18\x03 \x01(\v2\r.frr.DataTreeR\x06config\"\"\n" +
	"\bLoadType\x12\t\n" +
	"\x05MERGE\x10\x00\x12\v\n" +
	"\aREPLACE\x10\x01\"\x19\n" +
	"\x17LoadToCandidateResponse\"\xbf\x01\n" +
	"\rCommitRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\rR\vcandidateId\x12.\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x18.frr.CommitRequest.PhaseR\x05phase\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"A\n" +
	"\x05Phase\x12\f\n" +
	"\bVALIDATE\x10\x00\x12\v\n" +
	"\aPREPARE\x10\x01\x12\t\n" +
	"\x05ABORT\x10\x02\x12\t\n" +
	"\x05APPLY\x10\x03\x12\a\n" +
	"\x03ALL\x10\x04\"\\\n" +
	"\x0eCommitResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x19\n" +
	"\x17ListTransactionsRequest\"p\n" +
	"\x18ListTransactionsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06client\x18\x02 \x01(\tR\x06client\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"\x8e\x01\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12)\n" +
	"\bencoding\x18\x02 \x01(\x0e2\r.frr.EncodingR\bencoding\x12#\n" +
	"\rwith_defaults\x18\x03 \x01(\bR\fwithDefaults\"?\n" +
	"\x16GetTransactionResponse\x12%\n" +
	"\x06config\x18\x01 \x01(\v2\r.frr.DataTreeR\x06config\"\x13\n" +
	"\x11LockConfigRequest\"\x14\n" +
	"\x12LockConfigResponse\"\x15\n" +
	"\x13UnlockConfigRequest\"\x16\n" +
	"\x14UnlockConfigResponse\"J\n" +
	"\x0eExecuteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12$\n" +
	"\x05input\x18\x02 \x03(\v2\x0e.frr.PathValueR\x05input\"9\n" +
	"\x0fExecuteResponse\x12&\n" +
	"\x06output\x18\x01 \x03(\v2\x0e.frr.PathValueR\x06output\"`\n" +
	"\n" +
	"ModuleData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\forganization\x18\x02 \x01(\tR\forganization\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\"5\n" +
	"\tPathValue\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"I\n" +
	"\bDataTree\x12)\n" +
	"\bencoding\x18\x01 \x01(\x0e2\r.frr.EncodingR\bencoding\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data*\x1d\n" +
	"\bEncoding\x12\b\n" +
	"\x04JSON\x10\x00\x12\a\n" +
	"\x03XML\x10\x012\xab\a\n" +
	"\n" +
	"Northbound\x12N\n" +
	"\x0fGetCapabilities\x12\x1b.frr.GetCapabilitiesRequest\x1a\x1c.frr.GetCapabilitiesResponse\"\x00\x12,\n" +
	"\x03Get\x12\x0f.frr.GetRequest\x1a\x10.frr.GetResponse\"\x000\x01\x12N\n" +
	"\x0fCreateCandidate\x12\x1b.frr.CreateCandidateRequest\x1a\x1c.frr.CreateCandidateResponse\"\x00\x12N\n" +
	"\x0fDeleteCandidate\x12\x1b.frr.DeleteCandidateRequest\x1a\x1c.frr.DeleteCandidateResponse\"\x00\x12N\n" +
	"\x0fUpdateCandidate\x12\x1b.frr.UpdateCandidateRequest\x1a\x1c.frr.UpdateCandidateResponse\"\x00\x12H\n" +
	"\rEditCandidate\x12\x19.frr.EditCandidateRequest\x1a\x1a.frr.EditCandidateResponse\"\x00\x12N\n" +
	"\x0fLoadToCandidate\x12\x1b.frr.LoadToCandidateRequest\x1a\x1c.frr.LoadToCandidateResponse\"\x00\x123\n" +
	"\x06Commit\x12\x12.frr.CommitRequest\x1a\x13.frr.CommitResponse\"\x00\x12S\n" +
	"\x10ListTransactions\x12\x1c.frr.ListTransactionsRequest\x1a\x1d.frr.ListTransactionsResponse\"\x000\x01\x12K\n" +
	"\x0eGetTransaction\x12\x1a.frr.GetTransactionRequest\x1a\x1b.frr.GetTransactionResponse\"\x00\x12?\n" +
	"\n" +
	"LockConfig\x12\x16.frr.LockConfigRequest\x1a\x17.frr.LockConfigResponse\"\x00\x12E\n" +
	"\fUnlockConfig\x12\x18.frr.UnlockConfigRequest\x1a\x19.frr.UnlockConfigResponse\"\x00\x126\n" +
	"\aExecute\x12\x13.frr.ExecuteRequest\x1a\x14.frr.ExecuteResponse\"\x00b\x06proto3"

var (
	file_frrpb_frr_proto_rawDescOnce sync.Once
	file_frrpb_frr_proto_rawDescData []byte
)

func file_frrpb_frr_proto_rawDescGZIP() []byte {
	file_frrpb_frr_proto_rawDescOnce.Do(func() {
		file_frrpb_frr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frrpb_frr_proto_rawDesc), len(file_frrpb_frr_proto_rawDesc)))
	})
	return file_frrpb_frr_proto_rawDescData
}

var file_frrpb_frr_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_frrpb_frr_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_frrpb_frr_proto_goTypes = []any{
	(Encoding)(0),                        // 0: frr.Encoding
	(GetRequest_DataType)(0),             // 1: frr.GetRequest.DataType
	(LoadToCandidateRequest_LoadType)(0), // 2: frr.LoadToCandidateRequest.LoadType
	(CommitRequest_Phase)(0),             // 3: frr.CommitRequest.Phase
	(*GetCapabilitiesRequest)(nil),       // 4: frr.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil),      // 5: frr.GetCapabilitiesResponse
	(*GetRequest)(nil),                   // 6: frr.GetRequest
	(*GetResponse)(nil),                  // 7: frr.GetResponse
	(*CreateCandidateRequest)(nil),       // 8: frr.CreateCandidateRequest
	(*CreateCandidateResponse)(nil),      // 9: frr.CreateCandidateResponse
	(*DeleteCandidateRequest)(nil),       // 10: frr.DeleteCandidateRequest
	(*DeleteCandidateResponse)(nil),      // 11: frr.DeleteCandidateResponse
	(*UpdateCandidateRequest)(nil),       // 12: frr.UpdateCandidateRequest
	(*UpdateCandidateResponse)(nil),      // 13: frr.UpdateCandidateResponse
	(*EditCandidateRequest)(nil),         // 14: frr.EditCandidateRequest
	(*EditCandidateResponse)(nil),        // 15: frr.EditCandidateResponse
	(*LoadToCandidateRequest)(nil),       // 16: frr.LoadToCandidateRequest
	(*LoadToCandidateResponse)(nil),      // 17: frr.LoadToCandidateResponse
	(*CommitRequest)(nil),                // 18: frr.CommitRequest
	(*CommitResponse)(nil),               // 19: frr.CommitResponse
	(*ListTransactionsRequest)(nil),      // 20: frr.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),     // 21: frr.ListTransactionsResponse
	(*GetTransactionRequest)(nil),        // 22: frr.GetTransactionRequest
	(*GetTransactionResponse)(nil),       // 23: frr.GetTransactionResponse
	(*LockConfigRequest)(nil),            // 24: frr.LockConfigRequest
	(*LockConfigResponse)(nil),           // 25: frr.LockConfigResponse
	(*UnlockConfigRequest)(nil),          // 26: frr.UnlockConfigRequest
	(*UnlockConfigResponse)(nil),         // 27: frr.UnlockConfigResponse
	(*ExecuteRequest)(nil),               // 28: frr.ExecuteRequest
	(*ExecuteResponse)(nil),              // 29: frr.ExecuteResponse
	(*ModuleData)(nil),                   // 30: frr.ModuleData
	(*PathValue)(nil),                    // 31: frr.PathValue
	(*DataTree)(nil),                     // 32: frr.DataTree
}
var file_frrpb_frr_proto_depIdxs = []int32{
	30, // 0: frr.GetCapabilitiesResponse.supported_modules:type_name -> frr.ModuleData
	0,  // 1: frr.GetCapabilitiesResponse.supported_encodings:type_name -> frr.Encoding
	1,  // 2: frr.GetRequest.type:type_name -> frr.GetRequest.DataType
	0,  // 3: frr.GetRequest.encoding:type_name -> frr.Encoding
	32, // 4: frr.GetResponse.data:type_name -> frr.DataTree
	31, // 5: frr.EditCandidateRequest.update:type_name -> frr.PathValue
	31, // 6: frr.EditCandidateRequest.delete:type_name -> frr.PathValue
	2,  // 7: frr.LoadToCandidateRequest.type:type_name -> frr.LoadToCandidateRequest.LoadType
	32, // 8: frr.LoadToCandidateRequest.config:type_name -> frr.DataTree
	3,  // 9: frr.CommitRequest.phase:type_name -> frr.CommitRequest.Phase
	0,  // 10: frr.GetTransactionRequest.encoding:type_name -> frr.Encoding
	32, // 11: frr.GetTransactionResponse.config:type_name -> frr.DataTree
	31, // 12: frr.ExecuteRequest.input:type_name -> frr.PathValue
	31, // 13: frr.ExecuteResponse.output:type_name -> frr.PathValue
	0,  // 14: frr.DataTree.encoding:type_name -> frr.Encoding
	4,  // 15: frr.Northbound.GetCapabilities:input_type -> frr.GetCapabilitiesRequest
	6,  // 16: frr.Northbound.Get:input_type -> frr.GetRequest
	8,  // 17: frr.Northbound.CreateCandidate:input_type -> frr.CreateCandidateRequest
	10, // 18: frr.Northbound.DeleteCandidate:input_type -> frr.DeleteCandidateRequest
	12, // 19: frr.Northbound.UpdateCandidate:input_type -> frr.UpdateCandidateRequest
	14, // 20: frr.Northbound.EditCandidate:input_type -> frr.EditCandidateRequest
	16, // 21: frr.Northbound.LoadToCandidate:input_type -> frr.LoadToCandidateRequest
	18, // 22: frr.Northbound.Commit:input_type -> frr.CommitRequest
	20, // 23: frr.Northbound.ListTransactions:input_type -> frr.ListTransactionsRequest
	22, // 24: frr.Northbound.GetTransaction:input_type -> frr.GetTransactionRequest
	24, // 25: frr.Northbound.LockConfig:input_type -> frr.LockConfigRequest
	26, // 26: frr.Northbound.UnlockConfig:input_type -> frr.UnlockConfigRequest
	28, // 27: frr.Northbound.Execute:input_type -> frr.ExecuteRequest
	5,  // 28: frr.Northbound.GetCapabilities:output_type -> frr.GetCapabilitiesResponse
	7,  // 29: frr.Northbound.Get:output_type -> frr.GetResponse
	9,  // 30: frr.Northbound.CreateCandidate:output_type -> frr.CreateCandidateResponse
	11, // 31: frr.Northbound.DeleteCandidate:output_type -> frr.DeleteCandidateResponse
	13, // 32: frr.Northbound.UpdateCandidate:output_type -> frr.UpdateCandidateResponse
	15, // 33: frr.Northbound.EditCandidate:output_type -> frr.EditCandidateResponse
	17, // 34: frr.Northbound.LoadToCandidate:output_type -> frr.LoadToCandidateResponse
	19, // 35: frr.Northbound.Commit:output_type -> frr.CommitResponse
	21, // 36: frr.Northbound.ListTransactions:output_type -> frr.ListTransactionsResponse
	23, // 37: frr.Northbound.GetTransaction:output_type -> frr.GetTransactionResponse
	25, // 38: frr.Northbound.LockConfig:output_type -> frr.LockConfigResponse
	27, // 39: frr.Northbound.UnlockConfig:output_type -> frr.UnlockConfigResponse
	29, // 40: frr.Northbound.Execute:output_type -> frr.ExecuteResponse
	28, // [28:41] is the sub-list for method output_type
	15, // [15:28] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_frrpb_frr_proto_init() }
func file_frrpb_frr_proto_init() {
	if File_frrpb_frr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frrpb_frr_proto_rawDesc), len(file_frrpb_frr_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frrpb_frr_proto_goTypes,
		DependencyIndexes: file_frrpb_frr_proto_depIdxs,
		EnumInfos:         file_frrpb_frr_proto_enumTypes,
		MessageInfos:      file_frrpb_frr_proto_msgTypes,
	}.Build()
	File_frrpb_frr_proto = out.File
	file_frrpb_frr_proto_goTypes = nil
	file_frrpb_frr_proto_depIdxs = nil
}
