// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright 2019 FRRouting
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
// BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
// OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
// THE POSSIBILITY OF SUCH DAMAGE.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: frrpb/frr.proto

package frrpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Northbound_GetCapabilities_FullMethodName  = "/frr.Northbound/GetCapabilities"
	Northbound_Get_FullMethodName              = "/frr.Northbound/Get"
	Northbound_CreateCandidate_FullMethodName  = "/frr.Northbound/CreateCandidate"
	Northbound_DeleteCandidate_FullMethodName  = "/frr.Northbound/DeleteCandidate"
	Northbound_UpdateCandidate_FullMethodName  = "/frr.Northbound/UpdateCandidate"
	Northbound_EditCandidate_FullMethodName    = "/frr.Northbound/EditCandidate"
	Northbound_LoadToCandidate_FullMethodName  = "/frr.Northbound/LoadToCandidate"
	Northbound_Commit_FullMethodName           = "/frr.Northbound/Commit"
	Northbound_ListTransactions_FullMethodName = "/frr.Northbound/ListTransactions"
	Northbound_GetTransaction_FullMethodName   = "/frr.Northbound/GetTransaction"
	Northbound_LockConfig_FullMethodName       = "/frr.Northbound/LockConfig"
	Northbound_UnlockConfig_FullMethodName     = "/frr.Northbound/UnlockConfig"
	Northbound_Execute_FullMethodName          = "/frr.Northbound/Execute"
)

// NorthboundClient is the client API for Northbound service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service specification for the FRR northbound interface.
type NorthboundClient interface {
	// Retrieve the capabilities supported by the target.
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	// Retrieve configuration data, state data or both from the target.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error)
	// Create a new candidate configuration and return a reference to it. The
	// created candidate is a copy of the running configuration.
	CreateCandidate(ctx context.Context, in *CreateCandidateRequest, opts ...grpc.CallOption) (*CreateCandidateResponse, error)
	// Delete a candidate configuration.
	DeleteCandidate(ctx context.Context, in *DeleteCandidateRequest, opts ...grpc.CallOption) (*DeleteCandidateResponse, error)
	// Update a candidate configuration by rebasing the changes on top of the
	// latest running configuration. Resolve conflicts automatically by giving
	// preference to the changes done in the candidate configuration.
	UpdateCandidate(ctx context.Context, in *UpdateCandidateRequest, opts ...grpc.CallOption) (*UpdateCandidateResponse, error)
	// Edit a candidate configuration. All changes are discarded if any error
	// happens.
	EditCandidate(ctx context.Context, in *EditCandidateRequest, opts ...grpc.CallOption) (*EditCandidateResponse, error)
	// Load configuration data into a candidate configuration. Both merge and
	// replace semantics are supported.
	LoadToCandidate(ctx context.Context, in *LoadToCandidateRequest, opts ...grpc.CallOption) (*LoadToCandidateResponse, error)
	// Create a new configuration transaction using a two-phase commit protocol.
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// List the metadata of all configuration transactions recorded in the
	// transactions database.
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListTransactionsResponse], error)
	// Fetch a configuration (identified by its transaction ID) from the
	// transactions database.
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	// Lock the running configuration, preventing other users from changing it.
	LockConfig(ctx context.Context, in *LockConfigRequest, opts ...grpc.CallOption) (*LockConfigResponse, error)
	// Unlock the running configuration.
	UnlockConfig(ctx context.Context, in *UnlockConfigRequest, opts ...grpc.CallOption) (*UnlockConfigResponse, error)
	// Execute a YANG RPC.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type northboundClient struct {
	cc grpc.ClientConnInterface
}

func NewNorthboundClient(cc grpc.ClientConnInterface) NorthboundClient {
	return &northboundClient{cc}
}

func (c *northboundClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, Northbound_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Northbound_ServiceDesc.Streams[0], Northbound_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Northbound_GetClient = grpc.ServerStreamingClient[GetResponse]

func (c *northboundClient) CreateCandidate(ctx context.Context, in *CreateCandidateRequest, opts ...grpc.CallOption) (*CreateCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCandidateResponse)
	err := c.cc.Invoke(ctx, Northbound_CreateCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) DeleteCandidate(ctx context.Context, in *DeleteCandidateRequest, opts ...grpc.CallOption) (*DeleteCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCandidateResponse)
	err := c.cc.Invoke(ctx, Northbound_DeleteCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) UpdateCandidate(ctx context.Context, in *UpdateCandidateRequest, opts ...grpc.CallOption) (*UpdateCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCandidateResponse)
	err := c.cc.Invoke(ctx, Northbound_UpdateCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) EditCandidate(ctx context.Context, in *EditCandidateRequest, opts ...grpc.CallOption) (*EditCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditCandidateResponse)
	err := c.cc.Invoke(ctx, Northbound_EditCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) LoadToCandidate(ctx context.Context, in *LoadToCandidateRequest, opts ...grpc.CallOption) (*LoadToCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadToCandidateResponse)
	err := c.cc.Invoke(ctx, Northbound_LoadToCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, Northbound_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListTransactionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Northbound_ServiceDesc.Streams[1], Northbound_ListTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListTransactionsRequest, ListTransactionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Northbound_ListTransactionsClient = grpc.ServerStreamingClient[ListTransactionsResponse]

func (c *northboundClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, Northbound_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) LockConfig(ctx context.Context, in *LockConfigRequest, opts ...grpc.CallOption) (*LockConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockConfigResponse)
	err := c.cc.Invoke(ctx, Northbound_LockConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) UnlockConfig(ctx context.Context, in *UnlockConfigRequest, opts ...grpc.CallOption) (*UnlockConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockConfigResponse)
	err := c.cc.Invoke(ctx, Northbound_UnlockConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, Northbound_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NorthboundServer is the server API for Northbound service.
// All implementations must embed UnimplementedNorthboundServer
// for forward compatibility.
//
// Service specification for the FRR northbound interface.
type NorthboundServer interface {
	// Retrieve the capabilities supported by the target.
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	// Retrieve configuration data, state data or both from the target.
	Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error
	// Create a new candidate configuration and return a reference to it. The
	// created candidate is a copy of the running configuration.
	CreateCandidate(context.Context, *CreateCandidateRequest) (*CreateCandidateResponse, error)
	// Delete a candidate configuration.
	DeleteCandidate(context.Context, *DeleteCandidateRequest) (*DeleteCandidateResponse, error)
	// Update a candidate configuration by rebasing the changes on top of the
	// latest running configuration. Resolve conflicts automatically by giving
	// preference to the changes done in the candidate configuration.
	UpdateCandidate(context.Context, *UpdateCandidateRequest) (*UpdateCandidateResponse, error)
	// Edit a candidate configuration. All changes are discarded if any error
	// happens.
	EditCandidate(context.Context, *EditCandidateRequest) (*EditCandidateResponse, error)
	// Load configuration data into a candidate configuration. Both merge and
	// replace semantics are supported.
	LoadToCandidate(context.Context, *LoadToCandidateRequest) (*LoadToCandidateResponse, error)
	// Create a new configuration transaction using a two-phase commit protocol.
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// List the metadata of all configuration transactions recorded in the
	// transactions database.
	ListTransactions(*ListTransactionsRequest, grpc.ServerStreamingServer[ListTransactionsResponse]) error
	// Fetch a configuration (identified by its transaction ID) from the
	// transactions database.
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	// Lock the running configuration, preventing other users from changing it.
	LockConfig(context.Context, *LockConfigRequest) (*LockConfigResponse, error)
	// Unlock the running configuration.
	UnlockConfig(context.Context, *UnlockConfigRequest) (*UnlockConfigResponse, error)
	// Execute a YANG RPC.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedNorthboundServer()
}

// UnimplementedNorthboundServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNorthboundServer struct{}

func (UnimplementedNorthboundServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedNorthboundServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedNorthboundServer) CreateCandidate(context.Context, *CreateCandidateRequest) (*CreateCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCandidate not implemented")
}
func (UnimplementedNorthboundServer) DeleteCandidate(context.Context, *DeleteCandidateRequest) (*DeleteCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCandidate not implemented")
}
func (UnimplementedNorthboundServer) UpdateCandidate(context.Context, *UpdateCandidateRequest) (*UpdateCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCandidate not implemented")
}
func (UnimplementedNorthboundServer) EditCandidate(context.Context, *EditCandidateRequest) (*EditCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditCandidate not implemented")
}
func (UnimplementedNorthboundServer) LoadToCandidate(context.Context, *LoadToCandidateRequest) (*LoadToCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadToCandidate not implemented")
}
func (UnimplementedNorthboundServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedNorthboundServer) ListTransactions(*ListTransactionsRequest, grpc.ServerStreamingServer[ListTransactionsResponse]) error {
	return status.Error(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedNorthboundServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedNorthboundServer) LockConfig(context.Context, *LockConfigRequest) (*LockConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockConfig not implemented")
}
func (UnimplementedNorthboundServer) UnlockConfig(context.Context, *UnlockConfigRequest) (*UnlockConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockConfig not implemented")
}
func (UnimplementedNorthboundServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedNorthboundServer) mustEmbedUnimplementedNorthboundServer() {}
func (UnimplementedNorthboundServer) testEmbeddedByValue()                    {}

// UnsafeNorthboundServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NorthboundServer will
// result in compilation errors.
type UnsafeNorthboundServer interface {
	mustEmbedUnimplementedNorthboundServer()
}

func RegisterNorthboundServer(s grpc.ServiceRegistrar, srv NorthboundServer) {
	// If the following call panics, it indicates UnimplementedNorthboundServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Northbound_ServiceDesc, srv)
}

func _Northbound_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NorthboundServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Northbound_GetServer = grpc.ServerStreamingServer[GetResponse]

func _Northbound_CreateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).CreateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_CreateCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).CreateCandidate(ctx, req.(*CreateCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_DeleteCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).DeleteCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_DeleteCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).DeleteCandidate(ctx, req.(*DeleteCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_UpdateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).UpdateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_UpdateCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).UpdateCandidate(ctx, req.(*UpdateCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_EditCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).EditCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_EditCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).EditCandidate(ctx, req.(*EditCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_LoadToCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadToCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).LoadToCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_LoadToCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).LoadToCandidate(ctx, req.(*LoadToCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_ListTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NorthboundServer).ListTransactions(m, &grpc.GenericServerStream[ListTransactionsRequest, ListTransactionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Northbound_ListTransactionsServer = grpc.ServerStreamingServer[ListTransactionsResponse]

func _Northbound_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_LockConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).LockConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_LockConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).LockConfig(ctx, req.(*LockConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_UnlockConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).UnlockConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_UnlockConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).UnlockConfig(ctx, req.(*UnlockConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Northbound_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Northbound_ServiceDesc is the grpc.ServiceDesc for Northbound service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Northbound_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frr.Northbound",
	HandlerType: (*NorthboundServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _Northbound_GetCapabilities_Handler,
		},
		{
			MethodName: "CreateCandidate",
			Handler:    _Northbound_CreateCandidate_Handler,
		},
		{
			MethodName: "DeleteCandidate",
			Handler:    _Northbound_DeleteCandidate_Handler,
		},
		{
			MethodName: "UpdateCandidate",
			Handler:    _Northbound_UpdateCandidate_Handler,
		},
		{
			MethodName: "EditCandidate",
			Handler:    _Northbound_EditCandidate_Handler,
		},
		{
			MethodName: "LoadToCandidate",
			Handler:    _Northbound_LoadToCandidate_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Northbound_Commit_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _Northbound_GetTransaction_Handler,
		},
		{
			MethodName: "LockConfig",
			Handler:    _Northbound_LockConfig_Handler,
		},
		{
			MethodName: "UnlockConfig",
			Handler:    _Northbound_UnlockConfig_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Northbound_Execute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _Northbound_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListTransactions",
			Handler:       _Northbound_ListTransactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "frrpb/frr.proto",
}
